global:
  sendAnonymousUsage: false

log:
  level: "DEBUG"
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Cf-Connecting-Ip: keep
        X-Forwarded-For: keep
        X-Real-Ip: keep

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    swarmMode: false
  file:
    filename: /traefik_config.yml

api:
  dashboard: true
  debug: false
  insecure: false

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "secure"
          scheme: "https"
          permanent: true
  secure:
    address: ":443"
    http:
      middlewares:
        - secured-chain@file

certificatesResolvers:
  letsencrypt:
    acme:
      email: "corentin0pape@gmail.com"
      storage: "/srv/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: "EC256"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

experimental:
  plugins:
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
