---
- name: Use legacy for iptables
  become: true
  ansible.builtin.command: update-alternatives --set iptables /usr/sbin/iptables-legacy
  ignore_errors: true

- name: Use legacy for ip6tables
  become: true
  ansible.builtin.command: update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  ignore_errors: true

- name: Use legacy for arptables
  become: true
  ansible.builtin.command: update-alternatives --set arptables /usr/sbin/arptables-legacy
  ignore_errors: true

- name: Use legacy for ebtables
  become: true
  ansible.builtin.command: update-alternatives --set ebtables /usr/sbin/ebtables-legacy
  ignore_errors: true
