name: Deployment pipeline
on:
  push:
    branches:
      - main
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - nightly_maintenance_deploy
      - micro_services_deploy
  workflow_dispatch:

concurrency: deployment

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    container: infra/ci-tools:latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Deployment
        env:
          PASSBOLT_CI_ACS_BASE64: ${{secrets.PASSBOLT_CI_ACS_BASE64}}
          PASSBOLT_CI_PASSWORD: ${{secrets.PASSBOLT_CI_PASSWORD}}
          SSH_CI_PRIVATEKEY_BASE64: ${{secrets.SSH_CI_PRIVATEKEY_BASE64}}
        run: |
          ./ci-wrapper.sh ./terraform.sh apply -auto-approve -lock-timeout=5m
      - name: Deployment Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Deployment failed
            webhookUrl: ${{ secrets.CI_DISCORD_WEBHOOK }}
